version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: nova_senha
      MYSQL_DATABASE: clientes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./cliente.sql:/docker-entrypoint-initdb.d/cliente.sql

volumes:
  db_data:
